#define DRIPPING_CHANNEL -71324
#define DRIPPING_RESPONSE_CHANNEL -61325
#define PuddleVersion "2"
#define MAX_PUDDLES_TO_REZ_FROM_SAME_POSITION 30
#define PUDDLES_TO_REZ_FROM_SAME_POSITION_RESET_DURATION 60
